### ISSUE TITLE
AWS - Problem mit Organizations / IAM - Galina

### ISSUE THREAD

**Issue by Systemixx** [vServer-Hosting-Project/vserver-hosting#17]
AWS Konto für alle freigeben (AWS IAM bzw. Organizations)

AWS IAM Fehlermeldung:
![Image](https://github.com/vServer-Hosting-Project/vserver-hosting/assets/152193302/50959ba5-3b60-48b2-9384-f247c4f03a2b)

AWS Organizations Fehlermeldung:
![Image](https://github.com/vServer-Hosting-Project/vserver-hosting/assets/152193302/f5115330-8101-4bc4-9718-c076ebd2f1c7)

**Comment by atamankina** [comment]
Antwort vom Support: wir können eine Sandbox der Teilnehmer nehmen und ich kann allen zugriff auf diese Sandbox geben.
Dazu brauche ich die Sandbox, auf die alle wollen und die Naman der Teilnehmer die ich freischalten soll.

@Systemixx @Kuigan @Spiitzii 
TODO: bitte wählt aus, in welcher Sandbox ihr das Projekt implementieren möchtet.

**Comment by atamankina** [comment]
Berechtigungen angepasst.
