### ISSUE TITLE
AWS - Problem mit CloudShell (Galina)

### ISSUE THREAD

**Issue by Kuigan** [vServer-Hosting-Project/vserver-hosting#19]
Beim Aufrufen der CloudShell erscheint eine Fehlermeldung:

![Image](https://github.com/vServer-Hosting-Project/vserver-hosting/assets/152193302/4852188f-8009-434d-a9d4-195539a3b31a)

**Comment by atamankina** [comment]
working on permissions

**Comment by atamankina** [comment]
Berechtigungen angepasst.
