### ISSUE TITLE
AWS Domain SSL Zertifikat (Route53/Cognito) Problem - Galina

### ISSUE THREAD

**Issue by Kuigan** [vServer-Hosting-Project/vserver-hosting#29]
Um Cognito zum Laufen zu bringen, brauchen wir einen SSL Zertifikat (und dafür eine Domain). Leider haben wir keine Rechte dafür.

![Image](https://github.com/vServer-Hosting-Project/vserver-hosting/assets/152193302/ed9c9869-f00b-4035-b007-aff7adb9389f)

![Image](https://github.com/vServer-Hosting-Project/vserver-hosting/assets/152193302/3e6d14d9-a1a7-469f-a46e-301e3d1ae741)

![Image](https://github.com/vServer-Hosting-Project/vserver-hosting/assets/152193302/524bdb02-e93c-476d-a1ea-d040b7a1a853)

**Comment by atamankina** [comment]
@Kuigan teile bitte die Background Info mit, was versucht ihr in diesem Fall zu erreichen und welche Schritte habt ihr bisher ausgeführt. Fügt bitte relevante Links hinzu.

**Comment by atamankina** [comment]
Ich habe das Beispiel aus dem Developer Guide lokal implementiert, Cognito funktioniert auch ohne Verbindung mit Route53 oder ACM: https://docs.aws.amazon.com/cognito/latest/developerguide/getting-started-test-application-react.html
Könnt ihr bitte beschreiben, was ist euer Anwendungsfall, wenn ACM und Route53 nötig sind.

Schaut euch den Code der Testanwendung an, man implementiert Calls zu Cognito mit Hilfe von Cognito SDK: 
https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javascriptv3/example_code/cognito-identity-provider/scenarios/cognito-developer-guide-react-example/frontend-client/src/authService.ts

Schaut euch auch an, wie die React-Komponente miteinander interagieren:
https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/javascriptv3/example_code/cognito-identity-provider/scenarios/cognito-developer-guide-react-example/frontend-client/src

**Comment by Kuigan** [comment]
Vielen Dank für deine Rückmeldung und die Infos. Hattest du schon klären können, ob wir eine Domain durch Route53 für das Projekt bestellen können?

Bzgl. des Backgrounds, da melde ich mich noch mal nach dem morgigen Daily dazu.

**Comment by atamankina** [comment]
Ich brauche die Informationen zu dem Anwendungsfall, bevor ich das klären kann. Die meisten Konfigurationen gehen ohne der Einbeziehung der Domainservices.

**Comment by atamankina** [comment]
Route53 soll für euch freigeschaltet sein. Hier ist die relevante Dokumentation: https://docs.aws.amazon.com/de_de/Route53/latest/DeveloperGuide/MigratingDNS.html
