### ISSUE TITLE
AWS IAM Problem - Galina

### ISSUE THREAD

**Issue by Kuigan** [vServer-Hosting-Project/vserver-hosting#42]
Es fehlen Rechte, um neue Benutzer anzulegen (wird für Terraform benötigt)

![Image](https://github.com/vServer-Hosting-Project/vserver-hosting/assets/152193302/e6be0060-7ef2-4ae8-a0ca-035c8b81dcde)

**Comment by atamankina** [comment]
Investigating.

**Comment by atamankina** [comment]
@Kuigan @Systemixx möchtet ihr IAM User in Terraform Code erstellen oder möchtet Ihr IAM user benutzten damit die Terraform CLI sich authentifizieren kann?

**Comment by Kuigan** [comment]
Wir wollen, IAM user benutzten damit die Terraform CLI sich authentifizieren kann.

**Comment by Kuigan** [comment]
Link zum Tutorial:
https://www.youtube.com/watch?v=7xngnjfIlK4

**Comment by atamankina** [comment]
Ein neuer Benutzer kann nicht erstellt werden, benutzt eigene Credentials (Access Key ID und Secret Access Key), um mit Terraform zu arbeiten.

**Comment by Kuigan** [comment]
Das funktioniert leider nicht.

Hier ist die Fehlermeldung:
"An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records."

**Comment by Kuigan** [comment]
Wir haben es anders gelöst. Credentials in Code. Und es funktioiniert.
